listen:
  port: 8080

homeassistant:
  url: https://homeassistant.hollowoak.net
  token: ${HOMEASSISTANT_TOKEN}

models:
  default: qwen3:4b
  ollama_url: http://spark-a23e.hollowoak.net:11434
  local_first: true
  available:
    - name: qwen3:4b
      provider: ollama
      supports_tools: true
      context_window: 32768
      speed: 9
      quality: 7
      cost_tier: 0
      min_complexity: simple

data_dir: ./data
talents_dir: ./talents
